name: Lgpt

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_NAME: lgpt

jobs:
  build_linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller requests

      - name: Build Linux executable
        run: |
          pyinstaller --onefile --noconsole ${{ env.APP_NAME }}.py

      - name: Rename binary to lgpt-amd64
        run: |
          mkdir -p release
          mv dist/${{ env.APP_NAME }} release/lgpt-amd64

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: lgpt-amd64
          path: release/lgpt-amd64
